# Inherits from default config
# https://github.com/brigade/scss-lint/blob/master/config/default.yml

scss_files: 'src/**/*.scss'

linters:
  Indentation:
    character: tab
    width: 1

  LeadingZero:
    style: include_zero

  PropertySortOrder:
    order: smacss

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorFormat:
    enabled: false
