language: node_js
node_js: 8
script:
  - yarn test
  - yarn run build
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
env:
  global:
    # CHROME_CLIENT_ID
    - secure: mCLHKM8cOkJQghCLNcOrzQSCYhg5Cnu4cY0isxeOoLzC3iNgz1bAz/DwgEgTqEBKiGMY51bdMV9m/a54Bd56odwW2FL6ERgytND3TUz1IDKpe9F156eu1u8FtZ9W+sxzd4Jp+YzI0phPGB4fQYZkwkHqd5wprzOkGlSdUvr+kxlrh49iS1Cfq+BvcsMivYiVs9x8dr/WuxGiwFsuKuAWt0QcorT2b6RRSGSGx8jZS+DfS+EkD6t8ARqx4ioNgHM2wUuUXXbEb3quFmfM6uJe0Y07AwDrUGNLbOqweQz4/zg2hwXX3xOVRcSc2GTtUtAf8QjiogsljzBeszUMYpBrtWqphipcuoHIr8kbqeG/Wlvgbt6UkPXM4E0XD72wxVb1WAJb3mRDdo6O84qK5ynDU0TuSWaH2kZYMCoO0uRJATZHAevK/1G/6txgVKBmM+EiLClZp9mnq3bsFC69FBkWMoSG7BloD9FxS/wuX5OmXoG7A9tSeWecI94K8g/HiQENQDrXxp93sdaMkX0c0rUmBxUEbHAq0p/5E7eYrHqi4mJKkelCAoCXren5edkmK2H5ZFQLM86e6Ncsw3FqBjsn8wHuRAdrYg+X8YJ9Ny+rlsaiv8cCUJnGSw5WPEjYGh/Vvj30rBI7fe+xjMSwh0c4Ouxq421lFv6L9/UZEjArEfw=
    # CHROME_CLIENT_SECRET
    - secure: OondIHK7UWJMnRJTBz23hvBftm1oVr8l2uEhjvw4sl4WVoTwzgZxopTHlGV+LWrfnvv+RThpylKb/03Se4mV8H/GBoE3d8FNiNXN8i7ZlUrq1n99AQ192ludePtp1HYrjtWr5A8rB2xgxKZCqdmJjd7gZmxxPNJiZP6p/6uH9So28A1IqTBrSvx0XpFknlNW2a5FnCihaKDDFgLtbNqcKwJjjA/ThZEsnxXLhF3KYwb5jJRwM2zaH3QkFxckyI8jTb1qfg/tlIonOaot9NYkG2pXA5gqSHFzSNW1YvDncbQQ1sjL76Rpf/eR355Dr9n2BEJaF2ugdTgsUiry01p4X7B8nz+y56WeM9vogZLvi2mVLrgAqASkt3gx2uqyOdGqtFYJ21HaSQfzYm9Xl80KvrA17d+VlI6i4xzvcuNqk9jn7+m3ybaUxMy3sw5wL/mdFkZ1UzTp/yItQr8SvxrL/VgeqdvYa2iabX2goPiUP4lq5ZBwor/TLp5mSwWXLBy+KSRhc2pdi08D29ZKb6873lvFrtmwNJKxX3nhA0nk2zdJgZPy63MsJfu1zJC+2ernfrs+MP8nMjwzuzWSX8kRBR6oQKCB6dqMhhoFrri4Njmhx+807B7bzzRkOEkQjtzgobxp5wesQM529OlHGC0K4O5TcBTGfX6PR7sk1LQpvJM=
    # CHROME_REFRESH_TOKEN
    - secure: HJWlRlkeyD96li4CfLpG9UWXEvDDIRntv/+9qL5/5H7+hvscFiVYRIw3s9ZUcnHUfPcv+UyepvrxVBw+Q3dy8rLj1Tj3NG6JLJQMU0RufJOZ6M1Y1T+Zd6OoVDi8/8AFZWgVv1n3FqZ5DdlvzFZGYBtzkiNR19NVPfOOLjGng5c2yPVVaKVcSqe664AXuStCH5HnzgOCflSOiS6HzrKyPALLkFvncdic+qVUqAVJqw9T0bE8zrwrwzhj4Hev2f6TNFgFxpnIx/N2sx+Bbe8xbKvWvhrkGlpLtQaNh7o9wfAWxstyqfbAjGARhfHWrUWIpB9ZUetZBhMyrG/Ud/gpXn7FHHrzB++k/CoOY/09SBg0XWMOodGd9oqONj1DkhHgoVVZcJRDW8ubPpgTorg9/TAETeyn0IuzkVNUEeLn45CEsFTexBeNuF0REcDhYfRQ+y0PcwGTRdvNd15/CX844ZRhak90BNcSonrkxZ8guYWPnL0kIeE++R9jS7DrsWLrgZ4jY0WG+AEIO8vrUatB8A7jEaUVfJdZGtsmhQL/gR8JB0m8MsHPdcpmjG6F9gBPLoKb82Jlrg7znZ44UC7/IyYjbYGuncsm8VhKNB2oMHzDiFa+rtFELsanjavuyNBYa6oDYwfWEITBhUaIAm7I8/XwRwHmR201sdsVrEbEAps=
deploy:
  - provider: releases
    api_key:
      secure: FPa03/o+WBapHfFV3ZX9ShgQXyO5yHYcqH4S9a8wMbCNTz4M6+6RAf3ErsbDz5WlI11HzxCumVYsxxztaUCCWKJCNOgLOAkpLIQAPryq2X2wDfZDmCnWII2GNQj3FWequO8P57ZkXkkgZqqC6tGY00U6mIvNbIVm4QlY6wsDGd0izeR54z4OncDqOg09KTvHca1H/9K1MzachWhTbjtXEyaEJowV+GYvxb9cobPnowgtF42Iu5uz2ufLI5EfEeE8TyWuTXCKf+6THl2FvCKn4W/ss2H4F+lLgmb9uZs0kN2Adz3xCINCxlHbQXomqXKuAlG0gM1jTvuFmPjNES4Nr9FitqjXN9Ka0vaHjMc7iqUmjTUI3Znzn/2UrVF9KGEKJfeDUNvP8grz8puy62B7D/KzqHNNmLldpHB/2cWVcD2vCQlHwBhNBcr51olswvJe8EKByqPHZUiy4Jaoirdf/YJFJfWTacGg627sNFik3piBXEtIYT7wfdc9A652KBxXzAY6Gk0ddnDVVsNZ8g4dFzDUzkSfj4VAMKvrtFtbFEI2UhJ/VRW2Khm4jNlKZuvRSTqbWJgU9ZbZ8mAXnZI5ao0dUsafgBjUej27tp7XpTuRW6C1Ih7qDMYCdfg/voOFH2TZ8SK2btTR9YMIU+hHvBOiC3x2s8IQG8by7EZybog=
    file: dist/media-db.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: yarn run deploy
    skip_cleanup: true
    on:
      tags: true
